package othellogame.ui;

import javafx.application.*;
import javafx.stage.*;

/**
 * The GUI (Graphical User Interface) class is the entry point for the Othello game application.
 * <p>
 * It extends the JavaFX {@link Application} class and is responsible for launching the application.
 * @author Dinh Thuy Nhat Vy
 * @version 1.0, 12/07/2023
 * @see Controller
 */
public class GUI extends Application {
    /**
     * Default constructor for the {@code GUI} class.
     * <p>
     * Note: this constructor is automatically generated by the compiler and is not intended for direct use.
     */
    @SuppressWarnings("unused")
    public GUI() {}

    /**
     * The main method that launches the JavaFX application.
     * @param args command-line arguments passed to the application.
     */
    public static void main(String[] args) {
        launch(args);
    }

    /**
     * The start method is called when the JavaFX application is launched.
     * <p>
     * It initializes the {@link Controller} and updates the application.
     * @param primaryStage the primary stage for the application.
     * @throws Exception if an error occurs during application startup.
     */
    @Override
    public void start(Stage primaryStage) throws Exception {
        Controller controller = Controller.getInstance();
        controller.update();
    }
}