package othellogame.ui.view;

import javafx.fxml.*;
import javafx.scene.*;
import javafx.scene.layout.*;
import javafx.stage.*;
import othellogame.ui.*;

import java.io.*;
import java.util.*;

/**
 * Represents the controller for the {@code GameInstructionsScene} FXML file in the Othello game application.
 * <p>
 * It manages the UI elements and actions associated with the {@code GameInstructionsScene} FXML file.
 * <p>
 * Follows the Model-View-Controller (MVC) pattern.
 * @author Dinh Thuy Nhat Vy
 * @version 1.0, 12/07/2023
 * @see Controller
 */
public class GameInstructionsView {
    /**
     * Represents the game instructions pane in the {@code GameInstructionsScene} FXML file.
     */
    @FXML
    private Pane gameInstructions;

    /**
     * Default constructor for the {@code GameInstructionsView} class.
     * <p>
     * Note: this constructor is automatically generated by the compiler and is not intended for direct use.
     */
    public GameInstructionsView() {}

    /**
     * Loads the {@code GameInstructionsScene} FXML file by initializing the UI components and setting the scene.
     * @param currentPane the current pane from which the {@code GameInstructionsScene} is loaded.
     */
    public void loadGameInstructionsScene(Pane currentPane) {
        try {
            ResourceBundle bundle = ResourceBundle.getBundle("othellogame.ui.languages", Locale.getDefault());
            FXMLLoader loader = new FXMLLoader();
            Stage stage = (Stage) currentPane.getScene().getWindow();
            loader.setLocation(getClass().getResource("GameInstructionsScene.fxml"));
            loader.setResources(bundle);
            loader.setController(this);
            Parent root = loader.load();
            stage.getScene().setRoot(root);
        } catch (IOException e) {
            System.out.println("ERROR: [GameInstructionsScene] - " + e.getMessage());
        }
    }

    /**
     * Handles the action when the back button is clicked.
     * <p>
     * Navigates back to the previous scene.
     */
    @FXML
    private void onBackBtnClick() {
        Controller.getInstance().loadScene(Controller.previousScene, gameInstructions);
    }
}