package othellogame.ui.view;

import javafx.fxml.*;
import javafx.scene.*;
import javafx.scene.layout.*;
import javafx.stage.*;

import java.io.*;
import java.util.*;

/**
 * Represents the controller for the {@code ThankYouScene} FXML file in the Othello game application.
 * <p>
 * It is responsible for loading and displaying the {@code ThankYouScene} FXML file.
 * <p>
 * Follows the Model-View-Controller (MVC) pattern.
 * @author Dinh Thuy Nhat Vy
 * @version 1.0, 12/07/2023
 */
public class ThankYouView {
    /**
     * Default constructor for the {@code ThankYouView} class.
     * <p>
     * Note: this constructor is automatically generated by the compiler and is not intended for direct use.
     */
    public ThankYouView() {}

    /**
     * Loads and displays the {@code ThankYouScene}.
     * @param currentPane the current pane from which the {@code ThankYouScene} is loaded.
     */
    public void loadThankYouScene(Pane currentPane) {
        try {
            ResourceBundle bundle = ResourceBundle.getBundle("othellogame.ui.languages", Locale.getDefault());
            FXMLLoader loader = new FXMLLoader();
            Stage stage = (Stage) currentPane.getScene().getWindow();
            loader.setLocation(getClass().getResource("ThankYouScene.fxml"));
            loader.setResources(bundle);
            loader.setController(this);
            Parent root = loader.load();
            stage.getScene().setRoot(root);
        } catch (IOException e) {
            System.out.println("ERROR: [ThankYouScene] - " + e.getMessage());
        }
    }
}